=== Vedanttrivedi/xmlunit4/employee.xsd
<?xml version="1.0"?>
	<schema xmlns="http://www.w3.org/2001/XMLSchema">
		<element name="employee">
			<complexType>
				<sequence>
					<element name="boy" maxOccurs="1">
						<complexType>
							<sequence>
								<element name="fname" type="string" />
								<element name="lname" type="string" />
								<element name="age" type="int" />
							</sequence>
							</complexType>
						</element>
						<element name="girl" maxOccurs="1">
						<complexType>
							<sequence>
								<element name="fname" type="string" />
								<element name="lname" type="string" />
								<element name="age" type="int" />
							</sequence>
							</complexType>
						</element>
				</sequence>
			</complexType>
		</element>
	</schema>

=== Vedanttrivedi/xmlunit4/employee.xml
<?xml version="1.0"?>
	<employee xmlns="http://www.w3.org/2001/XMLSchema-instance" noNamespaceSchemaLocation="employee.xsd">
		
			<boy>
				<fname>Vedant</fname>
				<lname>Trivedi</lname>
				<age>18</age>
			</boy>
			
			<girl>
				<fname>Dhwani</fname>
				<lname>Trivedi</lname>
				<age>21</age>
			</girl>
		
	</employee>
